name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - mains

env:
  REGION: af-south-1
  REGISTRY: swr.af-south-1.myhuaweicloud.com/hw-ocp-org

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Build and push Docker images
        run: |

        
          
          docker build -t $REGISTRY/authentication:${{ github.sha }} ./authentication
          docker push $REGISTRY/authentication:${{ github.sha }}

          docker build -t $REGISTRY/transaction:${{ github.sha }} ./transaction
          docker push $REGISTRY/transaction:${{ github.sha }}

          docker build -t $REGISTRY/frontend:${{ github.sha }} ./frontend
          docker push $REGISTRY/frontend:${{ github.sha }}

